[build]
  command = "npm install --no-save lightningcss-linux-x64-gnu @tailwindcss/oxide-linux-x64-gnu && npx prisma generate && npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_HOSPITAL_NAME = "AIMS Prime Super Speciality Hospital"
  NEXT_PUBLIC_HOSPITAL_LOCATION = "Guntur, Andhra Pradesh, India"
  NEXT_PUBLIC_EMERGENCY_HOTLINE = "+91 863 234 5678"
  NEXT_PUBLIC_AMBULANCE_NUMBER = "+91 863 234 9999"
